#!/usr/bin/python3
# -*- coding: utf8 -*-

CHOICE_1 = "1"
CHOICE_2 = "2"
CHOICE_QUIT = "3"   
CHOICE_A = "a"
CHOICE_Z = "z"
CHOICE_S = "s"

HOME = "HOME"
CATEGORY_LIST = "CATEGORY_LIST"
SUBSTITUT = "SUBSTITUT"
PRODUIT_LIST = "PRODUIT_LIST"
PRODUIT_SELEC = "PRODUIT_SELEC"
SUBSTITUT_DISPLAY = "SUBSTITUT_DISPLAY"
